services:
  api:
    image: banking-app-api
    build:
      context: ..
      dockerfile: docker/Dockerfile

    container_name: banking-api

    ports:
      - "8000:8000"

    depends_on:
      - db

    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}

  db:
    image: mysql:8.0
    container_name: banking-db
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}

    ports:
      - "3008:3306"

    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: