services:
  banking-api:
    container_name: banking-api
    build:
      context: ../..
      dockerfile: docker/backend.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../..:/app
    env_file:
      - ../.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    networks:
      - shared-net

  banking-frontend:
    container_name: banking-frontend
    build:
      context: ../../frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ../../frontend:/app:Z
      - /app/node_modules
    depends_on:
      - banking-api
    restart: always
    networks:
      - shared-net

networks:
  shared-net:
    external: true
    name: shared-net